name: Sleeper
version: 1.4.1
description: Skip the night with a percentage or vote of players and an animation.
author: Hraponssi
main: sleeper.main.Main
api-version: 1.13
commands:
  ignoresleep:
    description: Make sleeper ignore if you sleep
    permission: sleeper.ignore
    usage: /ignoresleep
  sleepdata:
    description: See sleep data/debug
    permission: sleeper.data
    usage: /sleepdata
  sleepreload:
    description: Reload the sleeper config
    permission: sleeper.reload
    usage: /sleepreload
  sleep:
    description: Vote with subcommands
    permission: sleeper.sleep
    usage: /sleep
permissions:
  sleeper.*:
    description: Gives access to all commands for Sleeper.
    default: op
    children:
      sleeper.sleep: true
      sleeper.vote: true
      sleeper.reload: true
      sleeper.ignore: true
      sleeper.admin: true
  sleeper.sleep:
    description: Allows using /sleep
    default: true
  sleeper.vote:
    description: Allows voting on night skips.
    default: true
  sleeper.reload:
    description: Allows reloading the config of Sleeper.
    default: op
  sleeper.ignore:
    description: Allows you to toggle being ignored for sleeping.
    default: op
  sleeper.data:
    description: Allows debug of Sleeper.
    default: op